@echo off
setlocal EnableDelayedExpansion
echo.
echo =============================================
echo   PerfStudio — Docker Startup
echo =============================================
echo.

REM ── 1. Check Docker ───────────────────────────────────────────────────────
docker info >nul 2>&1
if %errorlevel% neq 0 (
  echo [ERROR] Docker is not running or not installed.
  echo.
  echo   Install Docker Desktop from:
  echo   https://www.docker.com/products/docker-desktop/
  echo.
  echo   After installing, start Docker Desktop and re-run this script.
  pause
  exit /b 1
)
echo [OK] Docker is running.

REM ── 2. Ensure required directories exist ──────────────────────────────────
if not exist "projects"       mkdir projects
if not exist "backups"        mkdir backups
if not exist "backend\data"   mkdir backend\data
echo [OK] Data directories ready.

REM ── 3. Set up .env.docker if it doesn't exist ─────────────────────────────
REM NOTE (fixed 2026-07-31): docker-compose.yml's PerfStudio service reads its runtime
REM env from `.env.docker` via `env_file:` — a plain `.env` is ONLY used by Compose for
REM its own %%VAR%% substitutions (image tag, PORT, tmpfs size) and never reaches the
REM container. This script used to write JWT_SECRET/etc. into `.env`, where the app
REM itself would never see them. Also new: the app refuses to boot without a reachable
REM S3 bucket (GDPR zero-local-disk design, since the 2026-07 migration).
if not exist ".env.docker" (
  echo [INFO] No .env.docker file found — creating from template...

  REM Generate a random JWT secret + encryption key using Node.js
  for /f "delims=" %%J in ('node -e "console.log(require('crypto').randomBytes(48).toString('hex'))" 2^>nul') do set JWT_VAL=%%J
  if "!JWT_VAL!"=="" set JWT_VAL=CHANGE_ME_run_node_to_generate_a_real_secret
  for /f "delims=" %%K in ('node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" 2^>nul') do set ENC_VAL=%%K
  if "!ENC_VAL!"=="" set ENC_VAL=CHANGE_ME_run_node_to_generate_a_real_key

  (
    echo # Auto-generated by docker-start.bat
    echo PORT=3001
    echo NODE_ENV=production
    echo JWT_SECRET=!JWT_VAL!
    echo ENCRYPTION_KEY=!ENC_VAL!
    echo CORS_ORIGIN=http://localhost:3001
    echo FRONTEND_URL=http://localhost:3001
    echo.
    echo REM ── REQUIRED — the app refuses to boot without a reachable S3 bucket ──
    echo REM GDPR zero-local-disk design: all git workspace data + test-run results
    echo REM live in S3 only. Fill these in before continuing ^(real AWS S3, or a
    echo REM local MinIO container — see docs\LOCAL_SETUP.md^), then re-run this script.
    echo S3_SYNC_ENABLED=true
    echo S3_BUCKET=CHANGE_ME_your_bucket_name
    echo S3_REGION=CHANGE_ME_your_region
  ) > .env.docker

  echo [OK] .env.docker created.
  echo [ACTION REQUIRED] Edit .env.docker and set S3_BUCKET / S3_REGION ^(and S3_ACCESS_KEY_ID/S3_SECRET_ACCESS_KEY
  echo                   if not running on AWS with an instance role^) before continuing — the app will not boot
  echo                   without a reachable S3 bucket. Re-run this script once done.
  pause
  exit /b 0
) else (
  echo [OK] .env.docker file found.
  findstr /C:"CHANGE_ME_your_bucket_name" .env.docker >nul 2>&1
  if !errorlevel! equ 0 (
    echo [ERROR] .env.docker still has a placeholder S3_BUCKET — edit it with your real bucket before continuing.
    pause
    exit /b 1
  )
)

REM ── 4. Build and start containers ─────────────────────────────────────────
echo.
echo [1/2] Building and starting containers...
docker compose --env-file .env.docker up --build -d

if %errorlevel% neq 0 (
  echo.
  echo [ERROR] docker compose failed. Check the output above.
  echo.
  echo   Common issues:
  echo   - Port 3001 already in use (check PORT in .env.docker)
  echo   - S3_BUCKET in .env.docker is unreachable (wrong region, missing credentials/permissions)
  echo   - Docker Desktop WSL2 backend needs restart
  pause
  exit /b 1
)

REM ── 5. Wait and open ──────────────────────────────────────────────────────
echo.
echo [2/2] Waiting for services to be healthy...
timeout /t 8 /nobreak >nul

echo.
echo =============================================
echo   PerfStudio is running!
echo.
echo   App : http://localhost:3001
echo   API : http://localhost:3001/api/health
echo.
echo   Default login: admin@perfstudio.com
echo   Default password: Admin@123
echo   (Change this after first login)
echo =============================================
echo.
echo   Next steps:
echo   1. Open Configuration ^> System Requirements ^> Run Check
echo   2. Pull Docker images in Configuration ^> Docker Engine
echo   3. Create your first project on the Dashboard
echo.
start http://localhost:3001
pause
