@echo off
setlocal EnableDelayedExpansion
echo.
echo =============================================
echo   PerfStudio — Docker Startup
echo =============================================
echo.

REM ── 1. Check Docker ───────────────────────────────────────────────────────
docker info >nul 2>&1
if %errorlevel% neq 0 (
  echo [ERROR] Docker is not running or not installed.
  echo.
  echo   Install Docker Desktop from:
  echo   https://www.docker.com/products/docker-desktop/
  echo.
  echo   After installing, start Docker Desktop and re-run this script.
  pause
  exit /b 1
)
echo [OK] Docker is running.

REM ── 2. Ensure required directories exist ──────────────────────────────────
if not exist "projects"       mkdir projects
if not exist "backups"        mkdir backups
if not exist "backend\data"   mkdir backend\data
echo [OK] Data directories ready.

REM ── 3. Set up .env if it doesn't exist ────────────────────────────────────
if not exist ".env" (
  echo [INFO] No .env file found — creating from template...

  REM Auto-detect absolute host path for projects folder (needed for Docker mounts)
  for %%I in ("%~dp0projects") do set PROJECTS_ABS=%%~fI
  for %%I in ("%~dp0backups")  do set BACKUPS_ABS=%%~fI

  REM Convert backslashes to forward slashes for Docker compatibility
  set PROJECTS_FWD=!PROJECTS_ABS:\=/!
  set BACKUPS_FWD=!BACKUPS_ABS:\=/!

  REM Generate a random JWT secret using Node.js
  for /f "delims=" %%J in ('node -e "console.log(require('crypto').randomBytes(48).toString('hex'))" 2^>nul') do set JWT_VAL=%%J
  if "!JWT_VAL!"=="" set JWT_VAL=CHANGE_ME_run_node_to_generate_a_real_secret

  (
    echo # Auto-generated by docker-start.bat
    echo PORT=3001
    echo NODE_ENV=production
    echo JWT_SECRET=!JWT_VAL!
    echo CORS_ORIGIN=http://localhost:5173
    echo PROJECTS_ROOT=/data/projects
    echo BACKUPS_ROOT=/data/backups
    echo HOST_PROJECTS_ROOT=!PROJECTS_FWD!
    echo HOST_BACKUPS_ROOT=!BACKUPS_FWD!
    echo BACKEND_PORT=3001
    echo FRONTEND_PORT=5173
    echo JMETER_DOCKER_IMAGE=justb4/jmeter:latest
    echo K6_DOCKER_IMAGE=grafana/k6:latest
  ) > .env

  echo [OK] .env created with HOST_PROJECTS_ROOT=!PROJECTS_FWD!
) else (
  echo [OK] .env file found.
)

REM ── 4. Build and start containers ─────────────────────────────────────────
echo.
echo [1/2] Building and starting containers...
docker compose up --build -d

if %errorlevel% neq 0 (
  echo.
  echo [ERROR] docker compose failed. Check the output above.
  echo.
  echo   Common issues:
  echo   - Port 3001 or 5173 already in use (check BACKEND_PORT / FRONTEND_PORT in .env)
  echo   - HOST_PROJECTS_ROOT path not accessible from Docker
  echo   - Docker Desktop WSL2 backend needs restart
  pause
  exit /b 1
)

REM ── 5. Wait and open ──────────────────────────────────────────────────────
echo.
echo [2/2] Waiting for services to be healthy...
timeout /t 8 /nobreak >nul

echo.
echo =============================================
echo   PerfStudio is running!
echo.
echo   App : http://localhost:5173
echo   API : http://localhost:3001/api/health
echo.
echo   Default login: admin@perfstudio.com
echo   Default password: Admin@123
echo   (Change this after first login)
echo =============================================
echo.
echo   Next steps:
echo   1. Open Configuration ^> System Requirements ^> Run Check
echo   2. Pull Docker images in Configuration ^> Docker Engine
echo   3. Create your first project on the Dashboard
echo.
start http://localhost:5173
pause
