#!/usr/bin/env bash
# ── PerfStudio — Linux/macOS Setup & Docker Startup ───────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "============================================="
echo "  PerfStudio — Docker Startup"
echo "============================================="
echo ""

# ── 1. Check Docker ─────────────────────────────────────────────────────────
if ! docker info >/dev/null 2>&1; then
  echo "[ERROR] Docker is not running or not installed."
  echo ""
  echo "  Linux:   curl -fsSL https://get.docker.com | sh"
  echo "           sudo usermod -aG docker \$USER && newgrp docker"
  echo "  macOS:   https://www.docker.com/products/docker-desktop/"
  echo ""
  exit 1
fi
echo "[OK] Docker is running."

# ── 2. Check Docker socket permission (Linux) ───────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
  if ! test -r /var/run/docker.sock || ! test -w /var/run/docker.sock; then
    echo "[WARN] Docker socket not accessible by current user."
    echo "  Fix: sudo usermod -aG docker \$USER && newgrp docker"
    echo "  Then re-run this script."
  fi
fi

# ── 3. Ensure required directories exist ────────────────────────────────────
mkdir -p projects backups backend/data
echo "[OK] Data directories ready."

# ── 4. Create .env.docker if it doesn't exist ───────────────────────────────
# NOTE (fixed 2026-07-31): docker-compose.yml's PerfStudio service reads its runtime
# env from `.env.docker` via `env_file:` — a plain `.env` at repo root is ONLY used by
# Compose for its own ${VAR} substitutions (image tag, PORT, tmpfs size) and is never
# passed into the container. This script used to write JWT_SECRET/etc. into `.env`,
# where the app itself would never see them. Also new: the app is a required, boot-
# blocking dependency on S3 (GDPR zero-local-disk design) since the 2026-07 migration —
# `docker compose up` will fail fast if S3_BUCKET is left as a placeholder.
if [[ ! -f ".env.docker" ]]; then
  echo "[INFO] No .env.docker file found — creating from template..."

  PROJECTS_ABS="$(cd projects && pwd)"
  BACKUPS_ABS="$(cd backups && pwd)"

  # Generate JWT secret + encryption key using Node.js if available, otherwise openssl
  if command -v node >/dev/null 2>&1; then
    JWT_VAL="$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")"
    ENC_VAL="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
  elif command -v openssl >/dev/null 2>&1; then
    JWT_VAL="$(openssl rand -hex 48)"
    ENC_VAL="$(openssl rand -hex 32)"
  else
    JWT_VAL="CHANGE_ME_install_node_or_openssl_to_generate_a_real_secret"
    ENC_VAL="CHANGE_ME_install_node_or_openssl_to_generate_a_real_key"
  fi

  cat > .env.docker <<EOF
# Auto-generated by setup.sh — review and customise before production
PORT=3001
NODE_ENV=production
JWT_SECRET=${JWT_VAL}
ENCRYPTION_KEY=${ENC_VAL}
CORS_ORIGIN=http://localhost:3001
FRONTEND_URL=http://localhost:3001

# ── REQUIRED — the app refuses to boot without a reachable S3 bucket ──
# GDPR zero-local-disk design: all git workspace data + test-run results live in S3
# only. Fill these in before continuing (real AWS S3, or a local MinIO container —
# see docs/LOCAL_SETUP.md for a MinIO example), then re-run this script.
S3_SYNC_ENABLED=true
S3_BUCKET=CHANGE_ME_your_bucket_name
S3_REGION=CHANGE_ME_your_region
EOF

  echo "[OK] .env.docker created."
  echo "[ACTION REQUIRED] Edit .env.docker and set S3_BUCKET / S3_REGION (and S3_ACCESS_KEY_ID/S3_SECRET_ACCESS_KEY"
  echo "                  if not running on AWS with an instance role) before continuing — the app will not boot"
  echo "                  without a reachable S3 bucket. Re-run this script once done."
  exit 0
else
  echo "[OK] .env.docker file found."
  if grep -q "CHANGE_ME_your_bucket_name" .env.docker 2>/dev/null; then
    echo "[ERROR] .env.docker still has a placeholder S3_BUCKET — edit it with your real bucket before continuing."
    exit 1
  fi
fi

# Compose's own ${VAR} substitutions (image tag, exposed PORT, tmpfs size) read from a
# plain `.env` at repo root, separate from `.env.docker` above — all have safe defaults,
# so no `.env` is required unless you want to override one of them.

# ── 5. Build and start containers ───────────────────────────────────────────
echo ""
echo "[1/2] Building and starting containers..."
docker compose --env-file .env.docker up --build -d

# ── 6. Wait for health ──────────────────────────────────────────────────────
echo ""
echo "[2/2] Waiting for services to be healthy..."
MAX=30
for i in $(seq 1 $MAX); do
  if curl -s http://localhost:3001/api/health | grep -q '"ok"'; then
    break
  fi
  sleep 2
done

echo ""
echo "============================================="
echo "  PerfStudio is running!"
echo ""
echo "  App : http://localhost:3001"
echo "  API : http://localhost:3001/api/health"
echo ""
echo "  Default login: admin@perfstudio.com"
echo "  Default password: Admin@123"
echo "  (Change this after first login)"
echo "============================================="
echo ""
echo "  Next steps:"
echo "  1. Open Configuration > System Requirements > Run Check"
echo "  2. Pull Docker images in Configuration > Docker Engine"
echo "  3. Create your first project on the Dashboard"
echo ""

# Open browser if possible
if command -v xdg-open >/dev/null 2>&1; then
  xdg-open http://localhost:3001 &
elif command -v open >/dev/null 2>&1; then
  open http://localhost:3001 &
fi
