#!/usr/bin/env bash
# ── PerfStudio — Linux/macOS Setup & Docker Startup ───────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "============================================="
echo "  PerfStudio — Docker Startup"
echo "============================================="
echo ""

# ── 1. Check Docker ─────────────────────────────────────────────────────────
if ! docker info >/dev/null 2>&1; then
  echo "[ERROR] Docker is not running or not installed."
  echo ""
  echo "  Linux:   curl -fsSL https://get.docker.com | sh"
  echo "           sudo usermod -aG docker \$USER && newgrp docker"
  echo "  macOS:   https://www.docker.com/products/docker-desktop/"
  echo ""
  exit 1
fi
echo "[OK] Docker is running."

# ── 2. Check Docker socket permission (Linux) ───────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
  if ! test -r /var/run/docker.sock || ! test -w /var/run/docker.sock; then
    echo "[WARN] Docker socket not accessible by current user."
    echo "  Fix: sudo usermod -aG docker \$USER && newgrp docker"
    echo "  Then re-run this script."
  fi
fi

# ── 3. Ensure required directories exist ────────────────────────────────────
mkdir -p projects backups backend/data
echo "[OK] Data directories ready."

# ── 4. Create .env if it doesn't exist ──────────────────────────────────────
if [[ ! -f ".env" ]]; then
  echo "[INFO] No .env file found — creating from template..."

  PROJECTS_ABS="$(cd projects && pwd)"
  BACKUPS_ABS="$(cd backups && pwd)"

  # Generate JWT secret using Node.js if available, otherwise openssl
  if command -v node >/dev/null 2>&1; then
    JWT_VAL="$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")"
  elif command -v openssl >/dev/null 2>&1; then
    JWT_VAL="$(openssl rand -hex 48)"
  else
    JWT_VAL="CHANGE_ME_install_node_or_openssl_to_generate_a_real_secret"
  fi

  cat > .env <<EOF
# Auto-generated by setup.sh — review and customise before production
PORT=3001
NODE_ENV=production
JWT_SECRET=${JWT_VAL}
CORS_ORIGIN=http://localhost:5173
PROJECTS_ROOT=/data/projects
BACKUPS_ROOT=/data/backups
HOST_PROJECTS_ROOT=${PROJECTS_ABS}
HOST_BACKUPS_ROOT=${BACKUPS_ABS}
BACKEND_PORT=3001
FRONTEND_PORT=5173
JMETER_DOCKER_IMAGE=justb4/jmeter:latest
K6_DOCKER_IMAGE=grafana/k6:latest
EOF

  echo "[OK] .env created with HOST_PROJECTS_ROOT=${PROJECTS_ABS}"
else
  echo "[OK] .env file found."
fi

# ── 5. Build and start containers ───────────────────────────────────────────
echo ""
echo "[1/2] Building and starting containers..."
docker compose up --build -d

# ── 6. Wait for health ──────────────────────────────────────────────────────
echo ""
echo "[2/2] Waiting for services to be healthy..."
MAX=30
for i in $(seq 1 $MAX); do
  if curl -s http://localhost:3001/api/health | grep -q '"ok"'; then
    break
  fi
  sleep 2
done

echo ""
echo "============================================="
echo "  PerfStudio is running!"
echo ""
echo "  App : http://localhost:5173"
echo "  API : http://localhost:3001/api/health"
echo ""
echo "  Default login: admin@perfstudio.com"
echo "  Default password: Admin@123"
echo "  (Change this after first login)"
echo "============================================="
echo ""
echo "  Next steps:"
echo "  1. Open Configuration > System Requirements > Run Check"
echo "  2. Pull Docker images in Configuration > Docker Engine"
echo "  3. Create your first project on the Dashboard"
echo ""

# Open browser if possible
if command -v xdg-open >/dev/null 2>&1; then
  xdg-open http://localhost:5173 &
elif command -v open >/dev/null 2>&1; then
  open http://localhost:5173 &
fi
