'use strict';
// k6-JS-aware counterparts of autoHealer.js's JMX-regex static-analysis helpers
// (extractVarRefs/extractDefinedVars/extractHostnames) — k6 scripts generated by
// buildK6Template (testSuites.js) are plain JS: template-literal interpolation for
// captured/correlated values, `const` declarations for User-Defined-Variable equivalents,
// and CSV data via SharedArray + papaparse destructuring — none of which the JMX regexes
// can see anything in.

// Every `${varName}` template-literal interpolation used inside the script — the k6
// equivalent of a JMeter ${VAR} reference. Skips bare property-access expressions
// (`${res.json().field}`) since those aren't variable REFERENCES needing a definition,
// only bare identifiers are.
function extractK6VarRefs(content) {
  const refs = new Set();
  for (const m of content.matchAll(/\$\{([A-Za-z_$][A-Za-z0-9_$]*)\}/g)) {
    if (m[1] !== '__ENV') refs.add(m[1]);
  }
  return [...refs];
}

// Every variable that HAS a definition in the script: top-level/function-scoped
// `const`/`let`/`var` declarations (covers plain assignment, captured-value extraction
// like `const token = res.json().access_token`, and CSV destructuring
// `const { col1, col2 } = row`), plus function parameters (the `data`/`row` a k6
// `export default function(data)` receives).
function extractK6DefinedVars(content) {
  const d = new Set();
  // const/let/var NAME = ...
  for (const m of content.matchAll(/\b(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=/g)) d.add(m[1]);
  // const/let/var { a, b, c } = ... (destructuring — CSV row columns, response fields)
  for (const m of content.matchAll(/\b(?:const|let|var)\s*\{([^}]+)\}\s*=/g)) {
    m[1].split(',').forEach(async part => {
      const name = part.split(':')[0].trim(); // handle `{ a: renamed }` — the binding is `renamed`... but split(':')[0] gives source key; prefer the last segment
      const bound = part.includes(':') ? part.split(':')[1].trim() : name;
      if (bound) d.add(bound.replace(/=.*/, '').trim());
    });
  }
  // function default export params, e.g. `export default function (data) {`
  for (const m of content.matchAll(/export\s+default\s+function\s*\(([^)]*)\)/g)) {
    m[1].split(',').forEach(async p => { const n = p.trim(); if (n) d.add(n); });
  }
  return [...d];
}

// The k6 equivalent of JMeter's HTTPSampler.domain/UDV-URL hostname scan: pull hostnames
// out of `const BASE_URL = __ENV.X || 'https://...'`-style defaults and any bare
// http(s):// literal in the script.
function extractK6Hostnames(content) {
  const hosts = new Set();
  for (const m of content.matchAll(/https?:\/\/[^\s'"`\\]+/g)) {
    try { const u = new URL(m[0]); if (u.hostname) hosts.add(u.hostname); } catch {}
  }
  return [...hosts];
}

module.exports = { extractK6VarRefs, extractK6DefinedVars, extractK6Hostnames };
